[theme]
base = "dark"
primaryColor = "#FF6B00"
backgroundColor = "#0F0F0F"
secondaryBackgroundColor = "#1C1C1C"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableStaticServing = true
